//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SubmitSys.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SubmitSys.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to function TypeText(id, text) {
        ///    var textbox = document.getElementById(id);
        ///    if (textbox)
        ///        textbox.setAttribute(&quot;value&quot;, text);
        ///}
        ///
        ///TypeText(&quot;username&quot;, &quot;D341302000&quot;);
        ///TypeText(&quot;password&quot;, &quot;3727990.yq&quot;);.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to function ClickTreeNode(root, nodeName) {
        ///    while (true) {
        ///        var treeNodes = root.getElementsByClassName(&apos;x-tree-node&apos;);
        ///        for (var i in treeNodes) {
        ///            if (treeNodes[i].getElementsByClassName) {
        ///                var anchorNode = treeNodes[i].getElementsByClassName(&apos;x-tree-node-anchor&apos;)[0];
        ///                if (anchorNode &amp;&amp; anchorNode.innerText == nodeName) {
        ///                    anchorNode.click();
        ///                    return treeNodes[i];
        ///                }
        ///            }
        ///      [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RunTime {
            get {
                return ResourceManager.GetString("RunTime", resourceCulture);
            }
        }
    }
}
