//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SubmitSys.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SubmitSys.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 错误.
        /// </summary>
        internal static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} 文件不存在，请检查....
        /// </summary>
        internal static string FileNotExistError {
            get {
                return ResourceManager.GetString("FileNotExistError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 信息.
        /// </summary>
        internal static string InfoTitle {
            get {
                return ResourceManager.GetString("InfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to function TypeText(id, text) {
        ///    var textbox = document.getElementById(id);
        ///    if (textbox)
        ///        textbox.setAttribute(&quot;value&quot;, text);
        ///}
        ///
        ///TypeText(&quot;username&quot;, &quot;D341302000&quot;);
        ///TypeText(&quot;password&quot;, &quot;3727990.yq&quot;);.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请先登录国家孕检系统....
        /// </summary>
        internal static string LoginInfoMessage {
            get {
                return ResourceManager.GetString("LoginInfoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择需要上传的数据文件.
        /// </summary>
        internal static string OpenFileTitle {
            get {
                return ResourceManager.GetString("OpenFileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 读取文件 {0} 失败，请检查文件格式和内容....
        /// </summary>
        internal static string ReadFileError {
            get {
                return ResourceManager.GetString("ReadFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无法读取字段影射文件 {0}.
        /// </summary>
        internal static string ReadMapFileError {
            get {
                return ResourceManager.GetString("ReadMapFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to function ClickTreeNode(r, n) {
        ///    while (true) {
        ///        var a = $(r).find(&apos;.x-tree-node-anchor:contains(&quot;&apos; + n + &apos;&quot;)&apos;);
        ///        if (a.length &gt; 0) {
        ///            a[0].click();
        ///            return a[0].closest(&apos;.x-tree-node&apos;);
        ///        }
        ///    }
        ///}
        ///
        ///function ClickTab(r, n) {
        ///    var t = $(r).find(&apos;.x-tab-strip-closable:contains(&quot;&apos; + n + &apos;&quot;)&apos;);
        ///    if (t.length &gt; 0) {
        ///        t[0].click();
        ///        return t[0];
        ///    } else {
        ///        return undefined;
        ///    }
        ///}
        ///
        ///function CloseTab(n) {
        ///    var tabs  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RunTime {
            get {
                return ResourceManager.GetString("RunTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择.
        /// </summary>
        internal static string SelectColumnName {
            get {
                return ResourceManager.GetString("SelectColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请选择需要上传的数据.
        /// </summary>
        internal static string SelectRecordsMessage {
            get {
                return ResourceManager.GetString("SelectRecordsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数据文件 (*.csv; *.zip)|*.csv; *.zip.
        /// </summary>
        internal static string SubmitFileFilter {
            get {
                return ResourceManager.GetString("SubmitFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在上传数据, 请稍等....
        /// </summary>
        internal static string Uploading {
            get {
                return ResourceManager.GetString("Uploading", resourceCulture);
            }
        }
    }
}
